name: Build DEB Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pack-deb.yml'
      - 'src/**'
      - 'share/**'
      - 'dpkg-conf/**'
      - 'Makefile'

jobs:
  build:
    name: Build DEB package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: dpkg compile
      working-directory: ./
      run: make pack-deb
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: origami-kernel.deb
        path: ./
    - name: Upload to telegram
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        TITLE: OKM DEB Package
      run: |
        DEB="okm-$(git rev-list HEAD --count)-$(git rev-parse --short HEAD)-gh.deb"
        mv origami-kernel.deb $DEB
        if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          export VERSION=$(git rev-list --count HEAD)
          bash $GITHUB_WORKSPACE/.github/scripts/telegram_bot.sh $GITHUB_WORKSPACE/$DEB
        fi